matrix:
  include:
    - language: java
      install: true
      jdk:
        - oraclejdk8
      script:
        - ./gradlew build

    - language: node_js
      node_js:
        - 10.15
      before_install:
        - cd Frontend
      install:
        - npm install
      script:
        - npm run build

    - stage: deploy to backend app
      script: skip
      deploy:
        provider: heroku
        api_key: 86799e0e-7d72-481f-a32b-76920d363c2c
        app: ecse321-group17

    - stage: deploy to frontend app
      script: skip
      deploy:
        provider: heroku
        api_key: 86799e0e-7d72-481f-a32b-76920d363c2c
        app: ecse321-group17-frontend
      on: travis-test
