matrix:
  include:
    - language: java
      install: true
      jdk:
        - oraclejdk8
      script:
        - ./gradlew build

    - language: node_js
      node_js:
        - 4.8
      before_install:
        - cd Frontend
      install:
        - npm install
      script:
        - npm start

deploy:
  provider: heroku
  api_key: 86799e0e-7d72-481f-a32b-76920d363c2c
  app: ecse321-group17
